using System.IO;
using UnityEngine;
using UnityEngine.Rendering;
using UnityEngine.EventSystems;
using UnityEngine.InputSystem.UI;
using UnityEditor;
using UnityEditor.SceneManagement;
using TMPro;
namespace Pigment.Editor {
public static class PigmentSceneBuilder {
    public const string Root="Assets/Pigment";
    static T Asset<T>(string path,System.Func<T> create) where T:Object {var a=AssetDatabase.LoadAssetAtPath<T>(path);if(a)return a;a=create();AssetDatabase.CreateAsset(a,path);return AssetDatabase.LoadAssetAtPath<T>(path);}
    static Material Lit(string name,Color color,Texture texture=null){return Asset(Root+"/Art/"+name+".mat",()=>{var m=new Material(Shader.Find("Universal Render Pipeline/Lit"));m.color=color;m.SetFloat("_Smoothness",.18f);if(texture)m.mainTexture=texture;return m;});}
    static GameObject Box(string name,Transform parent,Vector3 pos,Vector3 scale,Material mat){var o=GameObject.CreatePrimitive(PrimitiveType.Cube);o.name=name;o.transform.SetParent(parent,false);o.transform.localPosition=pos;o.transform.localScale=scale;o.GetComponent<MeshRenderer>().sharedMaterial=mat;Object.DestroyImmediate(o.GetComponent<Collider>());return o;}
    static Sprite SpriteAsset(string path,Texture2D t,bool rounded=false){File.WriteAllBytes(path,t.EncodeToPNG());Object.DestroyImmediate(t);AssetDatabase.ImportAsset(path);var imp=(TextureImporter)AssetImporter.GetAtPath(path);imp.textureType=TextureImporterType.Sprite;imp.spriteImportMode=SpriteImportMode.Single;imp.alphaIsTransparency=true;imp.mipmapEnabled=false;if(rounded)imp.spriteBorder=new Vector4(20,20,20,20);imp.SaveAndReimport();return AssetDatabase.LoadAssetAtPath<Sprite>(path);}
    static VesselDefinition Shape(string name,float h,float rb,float rt,float wall,float bottom,float bulge=0,float curve=1){var d=Asset(Root+"/Config/Vessels/"+name+".asset",()=>{var s=ScriptableObject.CreateInstance<VesselDefinition>();s.height=h;s.rBottom=rb;s.rTop=rt;s.wall=wall;s.baseThickness=bottom;s.bulge=bulge;s.curve=curve;return s;});d.glassMesh=Asset(Root+"/Art/"+name+"Mesh.asset",()=>VesselMesh.Glass(d));return d;}
    [MenuItem("Pigment/Create Game Scene")]
    public static void Build(){
        string scenePath=Root+"/Scenes/Pigment.unity";
        if(File.Exists(scenePath))throw new System.InvalidOperationException("Pigment scene already exists. Open it rather than overwriting authoring changes.");
        foreach(string dir in new[]{"Config","Config/Levels","Config/Vessels","Art","Prefabs","Scenes","Resources"})Directory.CreateDirectory(Root+"/"+dir);AssetDatabase.Refresh();
        var layout=Asset(Root+"/Config/BenchLayout.asset",()=>ScriptableObject.CreateInstance<PigmentLayout>());
        var rules=Asset(Root+"/Config/PourAndScoring.asset",()=>ScriptableObject.CreateInstance<PigmentRules>());
        var style=Asset(Root+"/Config/VisualsAndAudio.asset",()=>ScriptableObject.CreateInstance<PigmentStyle>());
        style.glass=Asset(Root+"/Art/Glass.mat",()=>new Material(Shader.Find("Pigment/Glass")));
        style.liquid=Asset(Root+"/Art/Liquid.mat",()=>new Material(Shader.Find("Pigment/Liquid")));
        var wood=Asset(Root+"/Art/Oak.asset",PigmentTextures.Wood);var stone=Asset(Root+"/Art/Stone.asset",PigmentTextures.Stone);var paper=Asset(Root+"/Art/Parchment.asset",PigmentTextures.Parchment);
        style.wood=Lit("Oak",Color.white,wood);style.wood.mainTextureScale=new Vector2(4.8f,3.12f);style.stone=Lit("Stone",new Color(.85f,.78f,.72f),stone);style.stone.mainTextureScale=new Vector2(6,4);style.parchment=Lit("Parchment",Color.white,paper);style.iron=Lit("Iron",new Color(.1f,.085f,.07f));
        style.roundedPanel=SpriteAsset(Root+"/Art/RoundedPanel.png",PigmentTextures.Rounded(),true);
        var handImporter=(TextureImporter)AssetImporter.GetAtPath(Root+"/Art/tutorialHand.png");handImporter.textureType=TextureImporterType.Sprite;handImporter.alphaIsTransparency=true;handImporter.mipmapEnabled=false;handImporter.SaveAndReimport();style.hand=AssetDatabase.LoadAssetAtPath<Sprite>(Root+"/Art/tutorialHand.png");
        Font font=AssetDatabase.LoadAssetAtPath<Font>("Assets/TextMesh Pro/Fonts/LiberationSans.ttf");
        style.font=TMP_FontAsset.CreateFontAsset(font,64,8,UnityEngine.TextCore.LowLevel.GlyphRenderMode.SDFAA,1024,1024,AtlasPopulationMode.Dynamic,true);style.font.name="Pigment Sans";AssetDatabase.CreateAsset(style.font,Root+"/Art/PigmentSans.asset");AssetDatabase.AddObjectToAsset(style.font.material,style.font);foreach(var atlas in style.font.atlasTextures)AssetDatabase.AddObjectToAsset(atlas,style.font);style.font.TryAddCharacters("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789ÇĞİÖŞÜçğıöşü%·—↻★☆! /",out string missing);EditorUtility.SetDirty(style.font);
        var mixer=Shape("Beaker",1.34f,.47f,.53f,.026f,.12f);var sample=Shape("Sample",.92f,.29f,.34f,.02f,.12f,.03f,1.2f);
        var shapes=new[]{Shape("Tumbler",1.04f,.31f,.38f,.022f,.13f),Shape("Highball",1.26f,.3f,.32f,.02f,.15f),Shape("Tulip",1.1f,.29f,.33f,.02f,.11f,.07f,1.4f),Shape("Rocks",.9f,.39f,.41f,.026f,.17f)};
        foreach(var d in new[]{mixer,sample,shapes[0],shapes[1],shapes[2],shapes[3]})MakePrefab(d,style);
        string[] names={"Turuncu","Yeşil","Magenta","Pembe","Lavanta","Petrol mavisi","Kiremit"};Vector4[] recipes={new Vector4(1,1,0,0),new Vector4(0,1,1,0),new Vector4(1,0,1,0),new Vector4(1,0,0,1.5f),new Vector4(1,0,1,2),new Vector4(0,1,2,1),new Vector4(2,1.5f,1,0)};int[][] ids={new[]{0,1},new[]{1,0,2},new[]{0,3,2},new[]{1,0,3},new[]{2,0,3,1},new[]{1,3,2,0},new[]{0,2,3,1}};var levels=new PigmentLevel[7];
        for(int i=0;i<7;i++){int n=i;levels[i]=Asset(Root+"/Config/Levels/"+(i+1).ToString("00")+"_"+names[i]+".asset",()=>{var l=ScriptableObject.CreateInstance<PigmentLevel>();l.id=n+1;l.displayName=names[n];l.recipe=recipes[n];l.sources=new PigmentId[ids[n].Length];for(int j=0;j<ids[n].Length;j++)l.sources[j]=(PigmentId)ids[n][j];return l;});}
        if(EditorSceneManager.GetActiveScene().isDirty)EditorSceneManager.SaveOpenScenes();
        var scene=EditorSceneManager.NewScene(NewSceneSetup.EmptyScene,NewSceneMode.Single);scene.name="Pigment";
        var root=new GameObject("Pigment Game");var game=root.AddComponent<PigmentGame>();game.layout=layout;game.rules=rules;game.style=style;game.levels=levels;game.mixerShape=mixer;game.sampleShape=sample;game.sourceShapes=shapes;
        game.vesselsRoot=new GameObject("Vessels • generated from level data").transform;game.vesselsRoot.SetParent(root.transform);
        var cameraObject=new GameObject("Main Camera",typeof(Camera),typeof(AudioListener));cameraObject.tag="MainCamera";game.gameCamera=cameraObject.GetComponent<Camera>();game.gameCamera.clearFlags=CameraClearFlags.SolidColor;game.gameCamera.backgroundColor=new Color(.11f,.09f,.065f);game.gameCamera.nearClipPlane=.05f;game.gameCamera.allowHDR=true;
        game.keyLight=Light("Warm Key",new Vector3(2.5f,7,-5),Quaternion.Euler(45,-25,0),style.keyColor,style.keyIntensity);Light("Soft Fill",new Vector3(-5,3.5f,2),Quaternion.Euler(25,130,0),Color.white,.35f);Light("Rim",new Vector3(-1.5f,5,6),Quaternion.Euler(35,180,0),new Color(1,.95f,.87f),.6f);
        RenderSettings.ambientMode=AmbientMode.Trilight;RenderSettings.ambientSkyColor=style.ambientSky*style.ambientIntensity;RenderSettings.ambientEquatorColor=new Color(.55f,.51f,.44f)*style.ambientIntensity;RenderSettings.ambientGroundColor=style.ambientGround*.45f;RenderSettings.skybox=null;
        var world=new GameObject("Alchemist Workshop").transform;BuildWorkshop(world,style);game.shelf=Box("Target Shelf",world,Vector3.zero,Vector3.one,Lit("Shelf",layout.goalShelf.color)).transform;
        game.effects=new GameObject("Pooled Effects").AddComponent<PigmentEffects>();var dot=Asset(Root+"/Art/SoftDot.asset",PigmentTextures.Dot);var particle=Asset(Root+"/Art/Particles.mat",()=>{var m=new Material(Shader.Find("Universal Render Pipeline/Particles/Unlit"));m.SetTexture("_BaseMap",dot);m.SetFloat("_Surface",1);m.SetFloat("_Blend",0);m.SetFloat("_SrcBlend",(float)BlendMode.SrcAlpha);m.SetFloat("_DstBlend",(float)BlendMode.OneMinusSrcAlpha);m.SetFloat("_ZWrite",0);m.EnableKeyword("_SURFACE_TYPE_TRANSPARENT");m.renderQueue=3000;return m;});
        game.effects.droplets=Particles("Splash & bubbles",game.effects.transform,particle,1.8f);game.effects.mist=Particles("Pigment vapor",game.effects.transform,particle,0);game.effects.sparks=Particles("Celebration",game.effects.transform,particle,1);game.effects.dust=Particles("Workshop dust",game.effects.transform,particle,0);var dm=game.effects.dust.main;dm.startLifetime=15;dm.startSpeed=.025f;dm.startSize=.022f;dm.startColor=new Color(1,.8f,.5f,.4f);var shape=game.effects.dust.shape;shape.enabled=true;shape.shapeType=ParticleSystemShapeType.Box;shape.scale=new Vector3(8,5,7);game.effects.dust.transform.position=new Vector3(0,2,1);var emission=game.effects.dust.emission;emission.enabled=true;emission.rateOverTime=4;
        game.audioPlayer=new GameObject("Synthesized Audio").AddComponent<PigmentAudio>();game.audioPlayer.style=style;game.hud=BuildHud(game,style);
        var es=new GameObject("EventSystem",typeof(EventSystem),typeof(InputSystemUIInputModule));es.GetComponent<InputSystemUIInputModule>().AssignDefaultActions();
        game.LoadLevel(0);game.RefreshVisuals(0);
        // Persist preview liquid meshes so vessels remain visible after reopening outside Play mode.
        int preview=0;foreach(var v in game.vesselsRoot.GetComponentsInChildren<VesselView>()){var mesh=Object.Instantiate(v.liquidFilter.sharedMesh);AssetDatabase.CreateAsset(mesh,Root+"/Art/PreviewLiquid"+(preview++)+".asset");v.liquidFilter.sharedMesh=mesh;}
        game.hud.startPanel.SetActive(false);game.hud.resultPanel.SetActive(false);game.hud.celebrationPanel.SetActive(false);game.hud.guide.SetActive(false);game.hud.targetName.text="Turuncu";game.hud.levelLabel.text="HEDEF RENK  ·  1/7";game.hud.targetTag.gameObject.SetActive(false);
        EditorUtility.SetDirty(style);EditorUtility.SetDirty(layout);AssetDatabase.SaveAssets();EditorSceneManager.SaveScene(scene,scenePath);EditorBuildSettings.scenes=new[]{new EditorBuildSettingsScene(scenePath,true)};PlayerSettings.companyName="Pigment Studio";PlayerSettings.productName="Pigment";PlayerSettings.defaultScreenWidth=540;PlayerSettings.defaultScreenHeight=960;PlayerSettings.defaultInterfaceOrientation=UIOrientation.AutoRotation;Application.targetFrameRate=60;
        Selection.activeObject=root;if(SceneView.lastActiveSceneView){SceneView.lastActiveSceneView.LookAt(new Vector3(0,1,0),game.gameCamera.transform.rotation,8);}
        AssetDatabase.SaveAssets();Debug.Log("PIGMENT_BUILD_OK: 7 levels, 6 vessel prefabs, editable layouts and rules; scene ready.");
    }
    static Light Light(string name,Vector3 pos,Quaternion rotation,Color color,float intensity){var o=new GameObject(name);o.transform.position=pos;o.transform.rotation=rotation;var l=o.AddComponent<Light>();l.type=LightType.Directional;l.color=color;l.intensity=intensity;l.shadows=LightShadows.Soft;return l;}
    static void MakePrefab(VesselDefinition d,PigmentStyle s){var o=new GameObject(d.name);var v=o.AddComponent<VesselView>();v.definition=d;var shell=new GameObject("Solid glass walls and rim",typeof(MeshFilter),typeof(MeshRenderer));shell.transform.SetParent(o.transform,false);v.shell=shell.GetComponent<MeshFilter>();v.shell.sharedMesh=d.glassMesh;shell.GetComponent<MeshRenderer>().sharedMaterial=s.glass;shell.GetComponent<MeshRenderer>().shadowCastingMode=ShadowCastingMode.Off;var liq=new GameObject("Gravity aligned liquid",typeof(MeshFilter),typeof(MeshRenderer));liq.transform.SetParent(o.transform,false);v.liquidFilter=liq.GetComponent<MeshFilter>();v.liquidRenderer=liq.GetComponent<MeshRenderer>();v.liquidRenderer.sharedMaterial=s.liquid;v.liquidRenderer.shadowCastingMode=ShadowCastingMode.Off;var collider=o.AddComponent<CapsuleCollider>();collider.center=Vector3.up*d.height*.5f;collider.height=d.height;collider.radius=Mathf.Max(d.rBottom,d.rTop);d.prefab=PrefabUtility.SaveAsPrefabAsset(o,Root+"/Prefabs/"+d.name+".prefab");Object.DestroyImmediate(o);EditorUtility.SetDirty(d);}
    static ParticleSystem Particles(string name,Transform parent,Material material,float gravity){var o=new GameObject(name);o.transform.SetParent(parent);var p=o.AddComponent<ParticleSystem>();p.Stop(true,ParticleSystemStopBehavior.StopEmittingAndClear);var m=p.main;m.playOnAwake=true;m.loop=true;m.maxParticles=200;m.simulationSpace=ParticleSystemSimulationSpace.World;m.gravityModifier=gravity;var e=p.emission;e.enabled=false;var s=p.shape;s.enabled=false;var color=p.colorOverLifetime;color.enabled=true;Gradient g=new Gradient();g.SetKeys(new[]{new GradientColorKey(Color.white,0),new GradientColorKey(Color.white,1)},new[]{new GradientAlphaKey(1,0),new GradientAlphaKey(0,1)});color.color=g;o.GetComponent<ParticleSystemRenderer>().sharedMaterial=material;return p;}
    static void BuildWorkshop(Transform world,PigmentStyle s){Box("Oak workbench",world,new Vector3(0,-.12f,-7.8f),new Vector3(48,.24f,24),s.wood);Box("Stone wall",world,new Vector3(0,12,4.22f),new Vector3(72,24,.08f),s.stone);var paper=GameObject.CreatePrimitive(PrimitiveType.Quad);paper.name="Ars Alchimia parchment";paper.transform.SetParent(world);paper.transform.position=new Vector3(2.3f,2.6f,4.15f);paper.transform.localScale=new Vector3(1.5f,2,1);paper.GetComponent<MeshRenderer>().sharedMaterial=s.parchment;Object.DestroyImmediate(paper.GetComponent<Collider>());var random=new System.Random(77);for(int side=0;side<2;side++){float x=side==0?-3.1f:2.6f,y=0;for(int i=0;i<4;i++){float h=.09f+(float)random.NextDouble()*.05f;var mat=Lit("Book"+side+"_"+i,Color.HSVToRGB((float)random.NextDouble(),.5f,.24f));var b=Box("Old alchemy book",world,new Vector3(x,y+h*.5f,3.6f),new Vector3(.7f+(float)random.NextDouble()*.2f,h,.55f),mat);b.transform.localEulerAngles=new Vector3(0,(float)random.NextDouble()*25-12,0);y+=h;}}
        var title=new GameObject("Parchment title",typeof(TextMeshPro));title.transform.SetParent(world);title.transform.position=new Vector3(2.3f,3.4f,4.09f);var text=title.GetComponent<TextMeshPro>();text.font=s.font;text.text="Ars Alchimia";text.fontSize=1.4f;text.alignment=TextAlignmentOptions.Center;text.color=new Color(.25f,.14f,.065f);text.rectTransform.sizeDelta=new Vector2(1.3f,.3f);
    }
    static RectTransform Rect(string name,Transform parent,Vector2 size,Vector2 anchor,Vector2 pos,Vector2? pivot=null){var o=new GameObject(name,typeof(RectTransform));var r=(RectTransform)o.transform;r.SetParent(parent,false);r.anchorMin=r.anchorMax=anchor;r.pivot=pivot??new Vector2(.5f,.5f);r.sizeDelta=size;r.anchoredPosition=pos;return r;}
    static UnityEngine.UI.Image Panel(string name,Transform parent,Vector2 size,Vector2 anchor,Vector2 pos,Color color,PigmentStyle style,bool block=false){var r=Rect(name,parent,size,anchor,pos);var im=r.gameObject.AddComponent<UnityEngine.UI.Image>();im.sprite=style.roundedPanel;im.type=UnityEngine.UI.Image.Type.Sliced;im.color=color;im.raycastTarget=block;return im;}
    static TextMeshProUGUI Text(string name,Transform parent,string value,float size,Vector2 dims,Vector2 pos,PigmentStyle style,TextAlignmentOptions align=TextAlignmentOptions.Center){var r=Rect(name,parent,dims,new Vector2(.5f,.5f),pos);var t=r.gameObject.AddComponent<TextMeshProUGUI>();t.font=style.font;t.text=value;t.fontSize=size;t.color=new Color(.96f,.9f,.81f);t.alignment=align;t.raycastTarget=false;t.fontStyle=FontStyles.Bold;t.textWrappingMode=TextWrappingModes.Normal;return t;}
    static UnityEngine.UI.Button Button(string name,Transform parent,string label,Vector2 size,Vector2 pos,PigmentStyle style,out TextMeshProUGUI text){var p=Panel(name,parent,size,new Vector2(.5f,.5f),pos,new Color(.77f,.51f,.22f),style,true);var b=p.gameObject.AddComponent<UnityEngine.UI.Button>();b.targetGraphic=p;var colors=b.colors;colors.highlightedColor=new Color(1,.9f,.7f);colors.pressedColor=new Color(.8f,.7f,.5f);b.colors=colors;text=Text("Label",p.transform,label,20,size-Vector2.one*12,Vector2.zero,style);return b;}
    static GameObject Overlay(string name,Transform parent,PigmentStyle style,float alpha){var root=Rect(name,parent,Vector2.zero,new Vector2(.5f,.5f),Vector2.zero);root.anchorMin=Vector2.zero;root.anchorMax=Vector2.one;root.offsetMin=root.offsetMax=Vector2.zero;var p=Panel("Dimmer",root,Vector2.zero,new Vector2(.5f,.5f),Vector2.zero,new Color(.08f,.045f,.025f,alpha),style,true);p.sprite=null;p.gameObject.AddComponent<FullCanvasDimmer>().Fit();return root.gameObject;}
    static PigmentHud BuildHud(PigmentGame game,PigmentStyle s){
        var go=new GameObject("Pigment HUD",typeof(RectTransform),typeof(Canvas),typeof(UnityEngine.UI.CanvasScaler),typeof(UnityEngine.UI.GraphicRaycaster));var hud=go.AddComponent<PigmentHud>();hud.game=game;hud.canvas=go.GetComponent<Canvas>();hud.canvas.renderMode=RenderMode.ScreenSpaceOverlay;hud.scaler=go.GetComponent<UnityEngine.UI.CanvasScaler>();hud.scaler.uiScaleMode=UnityEngine.UI.CanvasScaler.ScaleMode.ScaleWithScreenSize;hud.scaler.referenceResolution=new Vector2(450,800);hud.scaler.matchWidthOrHeight=0;
        hud.safeArea=Rect("Safe Area",go.transform,Vector2.zero,new Vector2(.5f,.5f),Vector2.zero);hud.safeArea.anchorMin=Vector2.zero;hud.safeArea.anchorMax=Vector2.one;hud.safeArea.offsetMin=hud.safeArea.offsetMax=Vector2.zero;
        var header=Panel("Target Card",hud.safeArea,new Vector2(420,88),new Vector2(.5f,1),new Vector2(0,-14),new Color(.102f,.067f,.047f,.9f),s);header.rectTransform.pivot=new Vector2(.5f,1);hud.header=header.rectTransform;
        hud.levelLabel=Text("Level",header.transform,"HEDEF RENK",11,new Vector2(300,18),new Vector2(-43,28),s,TextAlignmentOptions.Left);hud.levelLabel.characterSpacing=2;hud.levelLabel.color=new Color(.85f,.66f,.36f);hud.targetName=Text("Target",header.transform,"Turuncu",23,new Vector2(300,28),new Vector2(-43,5),s,TextAlignmentOptions.Left);
        var track=Panel("Fill Track",header.transform,new Vector2(300,8),new Vector2(.5f,.5f),new Vector2(-43,-25),new Color(1,1,1,.12f),s);hud.meter=Panel("Fill",track.transform,new Vector2(300,8),new Vector2(.5f,.5f),Vector2.zero,new Color(.78f,.36f,.92f),s);hud.meter.type=UnityEngine.UI.Image.Type.Filled;hud.meter.fillMethod=UnityEngine.UI.Image.FillMethod.Horizontal;hud.meter.fillAmount=0;hud.matchLabel=Text("Match",header.transform,"—",17,new Vector2(58,24),new Vector2(138,-23),s);hud.retry=Button("Retry",header.transform,"↻",new Vector2(40,40),new Vector2(170,16),s,out var retryText);retryText.fontSize=27;
        var tag=Panel("Target Tag",go.transform,new Vector2(136,29),new Vector2(.5f,.5f),Vector2.zero,new Color(.12f,.085f,.05f,.92f),s);hud.targetTag=tag.rectTransform;Text("Label",tag.transform,"HEDEF RENK",11,new Vector2(110,25),new Vector2(9,0),s);hud.tagDot=Panel("Swatch",tag.transform,new Vector2(10,10),new Vector2(.5f,.5f),new Vector2(-53,0),new Color(1,.45f,.02f),s);
        hud.hint=Text("Hint",go.transform,"Bir bardağa dokun, basılı tutarak dök",15,new Vector2(430,42),new Vector2(0,90),s);
        hud.guide=Rect("Tutorial",go.transform,Vector2.zero,new Vector2(.5f,.5f),Vector2.zero).gameObject;hud.hand=Rect("Hand",hud.guide.transform,new Vector2(115,138),new Vector2(.5f,.5f),Vector2.zero);var hand=hud.hand.gameObject.AddComponent<UnityEngine.UI.Image>();hand.sprite=s.hand;hand.raycastTarget=false;hand.preserveAspect=true;
        hud.startPanel=Overlay("Start",hud.safeArea,s,.25f);var title=Text("Title",hud.startPanel.transform,"PIGMENT",57,new Vector2(430,85),new Vector2(0,35),s);title.characterSpacing=8;Text("Subtitle",hud.startPanel.transform,"Renkleri karıştır, hedef rengi tuttur",16,new Vector2(420,35),new Vector2(0,-28),s);hud.play=Button("Play",hud.startPanel.transform,"BAŞLA",new Vector2(200,58),new Vector2(0,-110),s,out _);
        hud.resultPanel=Overlay("Result",hud.safeArea,s,.35f);var card=Panel("Result Card",hud.resultPanel.transform,new Vector2(370,420),new Vector2(.5f,.5f),Vector2.zero,new Color(.13f,.085f,.06f,.98f),s,true);hud.stars=Text("Stars",card.transform,"★  ★  ★",42,new Vector2(330,55),new Vector2(0,155),s);hud.percent=Text("Percent",card.transform,"%100",68,new Vector2(320,88),new Vector2(0,90),s);hud.verdict=Text("Verdict",card.transform,"Kusursuz karışım!",22,new Vector2(330,44),new Vector2(0,27),s);hud.want=Panel("Target Color",card.transform,new Vector2(68,68),new Vector2(.5f,.5f),new Vector2(-58,-48),Color.white,s);hud.got=Panel("Your Color",card.transform,new Vector2(68,68),new Vector2(.5f,.5f),new Vector2(58,-48),Color.white,s);Text("Target Caption",card.transform,"Hedef",13,new Vector2(85,24),new Vector2(-58,-96),s);Text("Your Caption",card.transform,"Senin",13,new Vector2(85,24),new Vector2(58,-96),s);hud.next=Button("Continue",card.transform,"Sonraki renk",new Vector2(290,55),new Vector2(0,-159),s,out hud.nextLabel);
        hud.celebrationPanel=Overlay("Celebration",hud.safeArea,s,.5f);Text("Title",hud.celebrationPanel.transform,"Tebrikler!",44,new Vector2(420,70),new Vector2(0,130),s);Text("Subtitle",hud.celebrationPanel.transform,"Bütün renkleri karıştırdın,\nusta simyacı oldun.",19,new Vector2(380,75),new Vector2(0,55),s);hud.totalStars=Text("Total Stars",hud.celebrationPanel.transform,"★  21 / 21",32,new Vector2(380,60),new Vector2(0,-25),s);hud.totalStars.color=new Color(1,.81f,.4f);hud.again=Button("Again",hud.celebrationPanel.transform,"Baştan oyna",new Vector2(250,56),new Vector2(0,-115),s,out _);
        InstallIcons(hud);PigmentHudGrouping.GroupTargetCard(hud);return hud;
    }
    public static void InstallIcons(PigmentHud hud){
        hud.retry.GetComponentInChildren<TextMeshProUGUI>().text="";
        if(!hud.retry.transform.Find("Refresh Icon"))Icon("Refresh Icon",hud.retry.transform,Vector2.zero,24,true);
        hud.stars.text="";hud.resultStarIcons=new PigmentIcon[3];
        for(int i=0;i<3;i++){var old=hud.stars.transform.Find("Star "+i);hud.resultStarIcons[i]=old?old.GetComponent<PigmentIcon>():Icon("Star "+i,hud.stars.transform,new Vector2((i-1)*63,0),42,false);}
        hud.totalStars.text="21 / 21";
        if(!hud.totalStars.transform.Find("Star"))Icon("Star",hud.totalStars.transform,new Vector2(-86,0),32,false);
        EditorUtility.SetDirty(hud);
    }
    static PigmentIcon Icon(string name,Transform parent,Vector2 pos,float size,bool refresh){var r=Rect(name,parent,Vector2.one*size,new Vector2(.5f,.5f),pos);var icon=r.gameObject.AddComponent<PigmentIcon>();icon.refresh=refresh;icon.raycastTarget=false;icon.color=new Color(1,.82f,.4f);return icon;}

}
}
